# Generated by Django 6.1.1 on 2026-09-23 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название типа инструмента')),
            ],
            options={
                'verbose_name': 'Тип инструмента',
                'verbose_name_plural': 'Типы инструментов',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField(unique=True, verbose_name='Тикер')),
                ('name', models.TextField(verbose_name='Название')),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Текущая цена')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instrument_logos/', verbose_name='Логотип')),
                ('instrument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrumenttype', verbose_name='Тип инструмента')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolio_covers/', verbose_name='Обложка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='Владелец портфеля')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Количество')),
                ('average_price', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Средняя цена')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument', verbose_name='Инструмент')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='market.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Цена')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='market.instrument', verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'История цен',
                'verbose_name_plural': 'Истории цен',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.TextField(choices=[('buy', 'Buy'), ('sell', 'Sell')], verbose_name='Тип заказа')),
                ('execution_type', models.TextField(choices=[('market', 'Market'), ('limit', 'Limit')], verbose_name='Тип исполнения')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Цена')),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='pending', verbose_name='Статус')),
                ('execution_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Цена исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Исполнено в')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trade_images/', verbose_name='Изображение')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument', verbose_name='Инструмент')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
