# Generated by Django 6.1.1 on 2026-09-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('portfolio', 'instrument')},
        ),
    ]
