# Generated by Django 6.1.1 on 2026-09-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_position_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='execution_type',
            field=models.TextField(choices=[('market', 'Рыночная'), ('limit', 'Лимитная')], verbose_name='Тип исполнения'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='order_type',
            field=models.TextField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.TextField(choices=[('pending', 'В ожидании'), ('executed', 'Исполнена'), ('cancelled', 'Отменена')], default='pending', verbose_name='Статус'),
        ),
    ]
